#!/bin/sh
set -eu

CONFIG_ROOT=${XDG_CONFIG_HOME:-"$HOME/.config"}
LAUNCHER_CONFIG=${VOCABBUILDER_LAUNCHER_CONFIG:-"$CONFIG_ROOT/vocabbuilder/remote.env"}
if [ -r "$LAUNCHER_CONFIG" ]; then
  # User-specific deployment identity belongs outside the public repository.
  # shellcheck disable=SC1090
  . "$LAUNCHER_CONFIG"
fi

REMOTE_HOST=${VOCABBUILDER_REMOTE_HOST:-vocabbuilder-mobile}
REMOTE_USER=${VOCABBUILDER_REMOTE_USER:-}
if [ -z "$REMOTE_USER" ]; then
  echo "Set VOCABBUILDER_REMOTE_USER in $LAUNCHER_CONFIG or your shell environment." >&2
  exit 2
fi
TARGET="$REMOTE_USER@$REMOTE_HOST"

REMOTE_COMMAND='sudo /usr/local/sbin/vocabbuilder-cli'
for argument in "$@"; do
  case "$argument" in
    *'
'*)
      echo "Command-line arguments cannot contain newlines." >&2
      exit 2
      ;;
  esac
  escaped_argument=$(printf '%s' "$argument" | sed "s/'/'\\\\''/g")
  REMOTE_COMMAND="$REMOTE_COMMAND '$escaped_argument'"
done

exec tailscale ssh "$TARGET" -t "$REMOTE_COMMAND"
